version: '3.7'

services:
  binance-dca-bot:
    restart: always
    container_name: binance-dca-boz
    image: binance-dca-bot:latest
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
